name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install lilbjson-c
      run: sudo apt install libjson-c-dev
    - name: create build dir
      run: mkdir -p ${{github.workspace}}/build
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build  -S ${{github.workspace}}/src
    - name: Build Project
      run: cd ${{github.workspace}}/build && make
