name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install libjson-c-dev libsqlite3-dev libncurses-dev libcurl-dev
    - name: Run CMake
      run: cmake -B ${{github.workspace}}/build  -S .
    - name: Build Project
      run: cd ${{github.workspace}}/build && make
    
